FLYNOBORDERS.SelfB2B.Web/Controllers/PackageDetailsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using FLYNOBORDERS.SelfB2B.Framework.Constant;
using FLYNOBORDERS.SelfB2B.Web.Framework.Bases;
using FLYNOBORDERS.SelfB2B.Web.Framework.Utils;

namespace FLYNOBORDERS.SelfB2B.Web.Controllers
{
    public class PackageDetailsController : BaseController
    {
        // GET: PackageDetails
        public ActionResult List(int pId)
        {
            if (HttpUtil.Current == null)
            {
                return RedirectToAction("Login", "Account");
            }

            var pd = Context.PackagePictures.FirstOrDefault(p => p.PID == pId);
            return View(pd);
        }

        public ActionResult Book(int pId)
        {
            if (HttpUtil.Current == null)
            {
                return RedirectToAction("Login", "Account");
            }
            var pd = Context.PackagePictures.FirstOrDefault(p => p.PID == pId);
            if (HttpUtil.Current.UserTypeID == (int) EnumCollection.UserTypeEnum.Admin)
            {
                return RedirectToAction("BookNow", "Admin", new { packageId = pId });
            }

            if (HttpUtil.Current.UserTypeID == (int)EnumCollection.UserTypeEnum.Agent)
            {
                return RedirectToAction("BookNow", "Agent", new {packageId = pId});
            }
            return View(pd);
        }
    }
}

FLYNOBORDERS.SelfB2B.Web/Views/PackageDetails/List.cshtml
@model FLYNOBORDERS.SelfB2B.Entities.PackagePicture
@{
    ViewBag.Title = "List";
    Layout = "~/Views/Shared/_AgentLayout.cshtml";
}

<h2 align="center">PACKAGE DETAILS WITH COST</h2>

<div class="body-content">

    <!-- Nav tabs -->
    <ul class="nav nav-tabs" role="tablist">
        <li role="presentation" class="active"><a href="#profile" aria-controls="home" role="tab" data-toggle="tab">PROFILE</a></li>
        <li role="presentation"><a href="#details" aria-controls="profile" role="tab" data-toggle="tab">DETAILS</a></li>
        <li role="presentation"><a href="#cost" aria-controls="messages" role="tab" data-toggle="tab">COST</a></li>
    </ul>

    <!-- Tab panes -->
    <div class="tab-content">
        <div role="tabpanel" class="tab-pane active" id="profile">PROFILE</div>
        <div role="tabpanel" class="tab-pane" id="details">DETAILS</div>
        <div role="tabpanel" class="tab-pane" id="cost">
            TOTAL COST : @Model.Price
            <br/>
            <a href="@Url.Action("Book", "PackageDetails", new {pId = @Model.PID})" class="btn btn-primary">Book Now</a>
        </div>
    </div>

</div>