FLYNOBORDERS.SelfB2B.Web/Controllers/AgentAccountsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Windows.Forms;
using FLYNOBORDERS.SelfB2B.Entities;
using FLYNOBORDERS.SelfB2B.Framework.Constant;
using FLYNOBORDERS.SelfB2B.Framework.Object;
using FLYNOBORDERS.SelfB2B.Model;
using FLYNOBORDERS.SelfB2B.Web.Framework.Attributes;
using FLYNOBORDERS.SelfB2B.Web.Framework.Bases;
using FLYNOBORDERS.SelfB2B.Web.Framework.Utils;

namespace FLYNOBORDERS.SelfB2B.Web.Controllers
{
    [SELFB2BAuthorize(EnumCollection.UserTypeEnum.Agent)]
    public class AgentAccountsController : BaseController
    {
        // GET: Admin

        public ActionResult GeneralLedger()
        {
            return View();
        }

        public ActionResult DepositRequest()
        {
            var depositeModel = new DepositeModel();
            return View(depositeModel);
        }

        [HttpPost]
        public ActionResult DepositRequest(DepositeModel model, HttpPostedFileBase image1)
        {
            /*if (!ModelState.IsValid)
            {
                return View(model);
            }*/

            if (image1 != null)
            {
                model.ReceiptImage = new byte[image1.ContentLength];
                image1.InputStream.Read(model.ReceiptImage, 0, image1.ContentLength);
            }

            var deposite = new Deposite()
            {
                DType = model.DType,
                ChequeNo = model.ChequeNo,
                RefNum = model.RefNum,
                ChequeBank = model.ChequeBank,
                Amount = model.Amount,
                Date = model.Date,
                BankId = model.BankId,
                ReceiptImage = model.ReceiptImage,
                UserID = HttpUtil.Current.ID,
                AdminVerifyId = (int)EnumCollection.AdminVarifyEnum.NotAccept
            };

            var result = DepositeRepo.Save(deposite);

            if (result.HasError == true)
            {
                ViewBag.Error = result.Message;
                return View(model);
            }
            //Context.Deposites.Add(deposite);
            //Context.SaveChanges();
            ViewBag.Success = "Your Deposite is send to Admin for Verify";
            return View();
        }

    }
}

FLYNOBORDERS.SelfB2B.Web/Controllers/AgentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using FLYNOBORDERS.SelfB2B.Entities;
using FLYNOBORDERS.SelfB2B.Framework.Constant;
using FLYNOBORDERS.SelfB2B.Framework.Object;
using FLYNOBORDERS.SelfB2B.Web.Framework.Attributes;
using FLYNOBORDERS.SelfB2B.Web.Framework.Bases;
using FLYNOBORDERS.SelfB2B.Web.Framework.Utils;
using FLYNOBORDERS.SelfB2B.Web.Framework.ViewModel;

namespace FLYNOBORDERS.SelfB2B.Web.Controllers
{
    [SELFB2BAuthorize(EnumCollection.UserTypeEnum.Agent)]
    public class AgentController : BaseController
    {
        // GET: Admin
        public ActionResult Index()
        {
            var userInfo = Context.UserInfos.FirstOrDefault(u => u.UID == HttpUtil.Current.ID);
            return View(userInfo);
        }

        public ActionResult UserProfile()
        {
            var result = UserInfoRepo.GetById(HttpUtil.Current.ID);

            if (result.HasError)
            {
                ViewBag.Error = result.Message;
                return RedirectToAction("Index", "Admin");
            }

            var userProfile = new UserInfo();

            return View(result);
        }

        [HttpPost]
        public ActionResult UserProfile(Result<UserInfo> userInfo, string pass, string cPass)
        {
            userInfo.Data.Pass = pass;
            /*if (!ModelState.IsValid)
            {
                return View(userInfo);
            }*/

            if (!pass.Equals(cPass))
            {
                return Content("Password and Confirm Password Should be Matched");
            }
            //userInfo.Data.Pass = pass;
            var result = UserInfoRepo.Save(userInfo.Data);

            if (result.HasError)
            {
                userInfo.HasError = true;
                userInfo.Message = result.Message;
                return View(userInfo);
            }

            return RedirectToAction("Index");
        }

        /*[HttpPost]
        public ActionResult UserProfile(string name)
        {
            return Content(name);
        }*/

        public ActionResult Reports()
        {
            return Content("Reports");
        }

        public ActionResult SearchPad(int packagePageNo = 1, int hotelPageNo = 1)
        {
            if (packagePageNo < 1)
                packagePageNo = 1;
            if (hotelPageNo < 1)
                hotelPageNo = 1;

            var pp = Context.PackagePictures.OrderByDescending(p => p.PID).Skip((packagePageNo - 1) * 4).Take(4).ToList();

            var hp = Context.HotelPictures.OrderByDescending(h => h.HID).Skip((hotelPageNo - 1) * 4).Take(4).ToList();



            var hpVM = new PackageHotelPictureVM()
            {
                PackagePictures = pp,
                HotelPictures = hp
            };

            ViewBag.PackageNext = packagePageNo + 1;
            ViewBag.PackagePrev = packagePageNo - 1;

            ViewBag.HotelNext = hotelPageNo + 1;
            ViewBag.HotelPrev = hotelPageNo - 1;

            return View(hpVM);
        }

        public ActionResult BookNow(int packageId)
        {
            var pd = Context.PackagePictures.FirstOrDefault(p => p.PID == packageId);
            //var ad = Context.UserInfos.FirstOrDefault(u => u.UID == HttpUtil.Current.ID);

            var puVM = new PackageUserInfoVM()
            {
                PackagePicture = pd,
                //UserInfo = ad
            };
            return View(pd);
        }

        [HttpPost]
        public ActionResult BookNow(PackagePicture packagePicture)
        {
            var ad = Context.UserInfos.FirstOrDefault(u => u.UID == HttpUtil.Current.ID);

            var result = BookingRepo.MinusBalance(HttpUtil.Current.ID, packagePicture.Price);

            if (result.HasError)
            {
                ViewBag.Error = result.Message;
                return Content(ViewBag.Error);
            }

            return Content("Successfully Booking Done");
        }


    }
}

FLYNOBORDERS.SelfB2B.Web/Controllers/AgentQueuesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using FLYNOBORDERS.SelfB2B.Entities;
using FLYNOBORDERS.SelfB2B.Framework.Constant;
using FLYNOBORDERS.SelfB2B.Framework.Object;
using FLYNOBORDERS.SelfB2B.Web.Framework.Attributes;
using FLYNOBORDERS.SelfB2B.Web.Framework.Bases;
using FLYNOBORDERS.SelfB2B.Web.Framework.Utils;

namespace FLYNOBORDERS.SelfB2B.Web.Controllers
{
    [SELFB2BAuthorize(EnumCollection.UserTypeEnum.Agent)]
    public class AgentQueuesController : BaseController
    {
        // GET: Admin

        public ActionResult OnHold()
        {
            return Content("On Hold");
        }

        public ActionResult Pending()
        {
            return Content("Pending");
        }

        public ActionResult Ticketed()
        {
            return Content("Ticketed");
        }

        public ActionResult Cancelled()
        {
            return Content("Cancelled");
        }

        public ActionResult RefundManagement()
        {
            return Content("Refund Management");
        }

        public ActionResult VoidManagement()
        {
            return Content("Void Management");
        }


    }
}

FLYNOBORDERS.SelfB2B.Web/Views/Shared/_AdminLayout.cshtml
@using FLYNOBORDERS.SelfB2B.Web.Framework.Utils
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-2">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href=@Url.Action("Index", "Admin")>NOBORDERS</a>
            </div>

            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-2">
                <ul class="nav navbar-nav">
                    <li><a href=@Url.Action("Index", "Admin")>HOME</a></li>
                    <li><a href="#">PACKAGE</a></li>     
                    <li><a href="#">VISA</a></li>    
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    <li id="SuMenu" class="menu"><a href=@Url.Action("UserProfile", "Admin")>Welcome, @HttpUtil.Current.LastName , @HttpUtil.Current.FirstName</a></li>
                    <li id="SiMenu" class="menu"><a href=@Url.Action("Logout", "Account")>LOGOUT</a></li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container-fluid body-content">
        @RenderBody()
        <hr />
        <footer style="background-color: lightcyan">
            <div class="row">
                <div class="col-md-4">
                    <img src="~/Content/Images/Website-Banner-002.jpg" style="width: 500px" height="400px" />
                </div>

                <div class="col-md-4">
                    <br />
                    <div class="input-group">
                        <input type="text" placeholder="Please Enter You E-Mail">
                        <button class="btn btn-success">Subscribe</button>
                    </div>
                    <br />
                    <p>
                        <a href="https://www.nobordersbd.com">NO BORDERS BD</a> is a next generation online travel platform for the tech savvy travelers worldwide.
                    </p>

                    <p>
                        <span class="glyphicon glyphicon-earphone"></span> &nbsp; +88-09638-800-600
                    </p>
                    <p>
                        <span class="glyphicon glyphicon-envelope"></span> &nbsp; info@nobordersbd.com
                    </p>

                    <p><b>QUICK LINKS</b></p>

                    <a href=@Url.Action("Index", "Home")>FLIGHT</a> <br />
                    <a href=@Url.Action("About", "Home")>PACKAGE</a> <br />
                    <a href=@Url.Action("Contact", "Home")>VISA</a> <br />

                </div>

                <div class="col-md-4" style="min-height: 70px; border-left: 1px solid black ">
                    <p>
                        Find us on Facebook
                    </p>
                    <p>
                        <b><i>ABOUT US</i></b>
                    </p>

                    <a href="#">WHO ARE WE?</a> <br />
                    <a href="#">WHY US?</a> <br />
                    <a href="#">SERVICES</a> <br />
                    <a href="#">TERMS & CONDITIONS</a> <br /> <br />

                    <p>
                        <b><i>LEGAL</i></b>
                    </p>

                    <a href="#">Transaction Confirmation</a> <br />
                    <a href="#">Amendment & Cancellation Policy</a> <br />
                    <a href="#">Privacy Policy </a> <br />
                </div>

            </div>


            <div class="row text-center">
                <div class="col-md-4">
                    <p> Developed By <a href="https://www.linkedin.com/in/samiul-siam-aa413a185/">SAS</a> & <a href="https://www.linkedin.com/in/ali-ahmed-akib-63bb91134/">AAA</a></p>
                </div>

                <div class="col-md-4">
                    <p>&copy; @DateTime.Now.Year - <a href="https://www.nobordersbd.com">NO BORDERS BD</a> All rights reserved.</p>
                </div>
                <div class="col-md-4">
                    Operational Address: Ka-4/1 (2<sup>nd</sup> Floor), Bashundhara Road, Dhaka-1229, Bangladesh.
                </div>
            </div>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

FLYNOBORDERS.SelfB2B.Web/Views/Shared/_AgentLayout.cshtml
@using FLYNOBORDERS.SelfB2B.Web.Controllers
@using FLYNOBORDERS.SelfB2B.Web.Framework.Utils
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <!--<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>-->
        <!-- <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script> --> 
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
    <body>
              
        <div class="fixed-top navbar navbar-light navbar-fixed-top navbar-expand-md navbar-inverse">
            <div class="container">
                <button type="button" class="navbar-toggler" data-toggle="collapse" data-target=".navbar-collapse">☰</button>
                <a class="navbar-brand" href=@Url.Action("Index", "Agent")>
                    NOBORDERSBD
                </a>
                <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                        <li class="nav-item">
                            <a href=@Url.Action("Index", "Agent") class="navbar-brand" style="font-size:medium">Home</a>
                        </li>

                        <li class="dropdown menu-large nav-item">
                            <a href="#" class="dropdown-toggle navbar-brand" data-toggle="dropdown" style="font-size:medium">Categories </a>
                            <ul class="dropdown-menu megamenu">
                                <div class="row">
                                    <li class="col-md-4 dropdown-item">
                                        <ul>

                                            <li>
                                                <a href=@Url.Action("Index", "Agent")>My Dashboard</a>
                                            </li>

                                            <li class="divider"></li>
                                            <li>
                                                <a href=@Url.Action("SearchPad", "Agent")>Search Pad</a>
                                            </li>
                                            <li class="divider"></li>
                                            <li class="dropdown-header">ADMINISTER</li>
                                            <li>
                                                <a href=@Url.Action("UserProfile", "Agent")>My Account</a>
                                            </li>


                                        </ul>
                                    </li>
                                    <li class="col-md-4 dropdown-item">
                                        <ul>
                                            <li class="dropdown-header">ACCCOUNTS</li>
                                            <li>
                                                <a href=@Url.Action("GeneralLedger", "AgentAccounts")>General Ledger</a>
                                            </li>
                                            <li>
                                                <a href=@Url.Action("DepositRequest", "AgentAccounts")>Deposit Request</a>
                                            </li>

                                            <li class="divider"></li>
                                            <li>
                                                <a href=@Url.Action("Reports", "Agent")>Reports</a>
                                            </li>

                                        </ul>
                                    </li>
                                    <li class="col-md-4 dropdown-item">
                                        <ul>
                                            <li class="dropdown-header">QUEUES</li>
                                            <li>
                                                <a href=@Url.Action("OnHold", "AgentQueues")>On Hold</a>
                                            </li>
                                            <li>
                                                <a href=@Url.Action("Pending", "AgentQueues")>Pending</a>
                                            </li>
                                            <li>
                                                <a href=@Url.Action("Ticketed", "AgentQueues")>Ticketed</a>
                                            </li>
                                            <li>
                                                <a href=@Url.Action("Cancelled", "AgentQueues")>Cancelled</a>
                                            </li>
                                            <li>
                                                <a href=@Url.Action("RefundManagement", "AgentQueues")>Refund Management</a>
                                            </li>
                                            <li>
                                                <a href=@Url.Action("VoidManagement", "AgentQueues")>Void Management</a>
                                            </li>

                                        </ul>
                                    </li>

                                </div>
                            </ul>
                        </li>
                    </ul>
                
                    <ul class="nav navbar-nav navbar-right">
                        <li id="SuMenu" class="menu"><a href=@Url.Action("UserProfile", "Agent")>Welcome, @HttpUtil.Current.LastName , @HttpUtil.Current.FirstName</a></li>
                        <li id="SiMenu" class="menu"><a href=@Url.Action("Logout", "Account")>LOGOUT</a></li>
                    </ul>
                </div>
            </div>
        </div>

        <div class="container-fluid body-content">
            @RenderBody()
            <hr />
            <footer style="background-color: lightcyan">
                <div class="row">
                    <div class="col-md-4">
                        <img src="~/Content/Images/Website-Banner-002.jpg" style="width: 500px" height="400px" />
                    </div>

                    <div class="col-md-4">
                        <br />
                        <div class="input-group">
                            <input type="text" placeholder="Please Enter You E-Mail">
                            <button class="btn btn-success">Subscribe</button>
                        </div>
                        <br />
                        <p>
                            <a href="https://www.nobordersbd.com">NO BORDERS BD</a> is a next generation online travel platform for the tech savvy travelers worldwide.
                        </p>

                        <p>
                            <span class="glyphicon glyphicon-earphone"></span> &nbsp; +88-09638-800-600
                        </p>
                        <p>
                            <span class="glyphicon glyphicon-envelope"></span> &nbsp; info@nobordersbd.com
                        </p>

                        <p><b>QUICK LINKS</b></p>

                        <a href=@Url.Action("Index", "Home")>FLIGHT</a> <br />
                        <a href=@Url.Action("About", "Home")>PACKAGE</a> <br />
                        <a href=@Url.Action("Contact", "Home")>VISA</a> <br />

                    </div>

                    <div class="col-md-4" style="min-height: 70px; border-left: 1px solid black ">
                        <p>
                            Find us on Facebook
                        </p>
                        <p>
                            <b><i>ABOUT US</i></b>
                        </p>

                        <a href="#">WHO ARE WE?</a> <br />
                        <a href="#">WHY US?</a> <br />
                        <a href="#">SERVICES</a> <br />
                        <a href="#">TERMS & CONDITIONS</a> <br /> <br />

                        <p>
                            <b><i>LEGAL</i></b>
                        </p>

                        <a href="#">Transaction Confirmation</a> <br />
                        <a href="#">Amendment & Cancellation Policy</a> <br />
                        <a href="#">Privacy Policy </a> <br />
                    </div>

                </div>


                <div class="row text-center">
                    <div class="col-md-4">
                        <p> Developed By <a href="https://www.linkedin.com/in/samiul-siam-aa413a185/">SAS</a> & <a href="https://www.linkedin.com/in/ali-ahmed-akib-63bb91134/">AAA</a></p>
                    </div>

                    <div class="col-md-4">
                        <p>&copy; @DateTime.Now.Year - <a href="https://www.nobordersbd.com">NO BORDERS BD</a> All rights reserved.</p>
                    </div>
                    <div class="col-md-4">
                        Operational Address: Ka-4/1 (2<sup>nd</sup> Floor), Bashundhara Road, Dhaka-1229, Bangladesh.
                    </div>
                </div>
            </footer>
        </div>

        @Scripts.Render("~/bundles/jquery")
        @Scripts.Render("~/bundles/bootstrap")
        @RenderSection("scripts", required: false)
    </body>
</html>

<style>
    .navbar-light {
        color: #fff;
        background-color: #18BC9C;
        border-color: #aca1a2;
    }

        .navbar-light .navbar-nav > li > a {
            color: #fff;
        }

        .navbar-light .nav-link {
            color: white;
        }

        .navbar-light .navbar-nav > .dropdown > a .caret {
            border-top-color: #fff;
            border-bottom-color: #fff;
        }

        .navbar-light .navbar-brand {
            color: #fff;
        }



    .menu-large {
        position: static !important;
    }

    .megamenu {
        padding: 20px 20px;
        width: 70%;
    }

        .megamenu > div > li > ul {
            padding: 0;
            margin: 0;
        }

            .megamenu > div > li > ul > li {
                list-style: none;
            }

        .megamenu .card {
            outline: none;
        }

            .megamenu .card:hover,
            .megamenu .card:focus {
                outline: 1px solid #000;
            }

        .megamenu > div > li > ul > li > a {
            display: block;
            padding: 3px 20px;
            clear: both;
            font-weight: normal;
            line-height: 1.428571429;
            color: #333333;
            white-space: normal;
        }

            .megamenu > div > li > ul > li > a:hover,
            .megamenu > div > li > ul > li > a:focus {
                text-decoration: none;
                color: #262626;
                background-color: #f5f5f5;
            }

        .megamenu.disabled > a,
        .megamenu.disabled > a:hover,
        .megamenu.disabled > a:focus {
            color: #999999;
        }

            .megamenu.disabled > a:hover,
            .megamenu.disabled > a:focus {
                text-decoration: none;
                background-color: transparent;
                background-image: none;
                filter: progid: DXImageTransform.Microsoft.gradient(enabled=false);
                cursor: not-allowed;
            }

        .megamenu.dropdown-header {
            color: #fff;
            font-size: 20px;
        }

    @@media (max-width: 768px) {
        .megamenu {
            margin-left: 0;
            margin-right: 0;
        }

            .megamenu > li {
                margin-bottom: 30px;
            }

                .megamenu > li:last-child {
                    margin-bottom: 0;
                }

            .megamenu.dropdown-header {
                padding: 3px 15px !important;
            }

        .navbar-nav .open .dropdown-menu .dropdown-header {
            color: #fff;
        }
    }
</style>

FLYNOBORDERS.SelfB2B.Web/Views/Shared/_InnerLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    
    <div class="container-fluid body-content">
        @RenderBody()
        <hr />
        
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

FLYNOBORDERS.SelfB2B.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-2">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="#">NOBORDERS</a>
            </div>

            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-2">
                <ul class="nav navbar-nav">
                    <li id="homeMenu" class="menu"><a href=@Url.Action("Index", "Home")> <b>FLIGHT</b>  </a></li>
                    <li id="abtMenu" class="menu"><a href=@Url.Action("Package", "Home")><b>PACKAGES</b></a></li>
                    <li id="conMenu" class="menu"><a href=@Url.Action("Visa", "Home")><b>VISA</b></a></li>    
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    <li id="NuMenu" class="menu"><a href=@Url.Action("Registration", "Account")> <span class="glyphicon glyphicon-phone-alt"></span> &nbsp; +88-09638-800-600</a></li>
                    <li id="SuMenu" class="menu"><a href=@Url.Action("Registration", "Account")>REGISTER</a></li>
                    <li id="SiMenu" class="menu"><a href=@Url.Action("Login", "Account")>BUSINESS LOGIN</a></li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container-fluid body-content">
        @RenderBody()
        <hr />
        <footer style="background-color: lightcyan">
            <div class="row">
                <div class="col-md-4">
                    <img src="~/Content/Images/Website-Banner-002.jpg" style="width: 500px" height="400px" />
                </div>

                <div class="col-md-4">
                    <br />
                    <div class="input-group">
                        <input type="text" placeholder="Please Enter You E-Mail">
                        <button class="btn btn-success">Subscribe</button>
                    </div>
                    <br />
                    <p>
                        <a href="https://www.nobordersbd.com">NO BORDERS BD</a> is a next generation online travel platform for the tech savvy travelers worldwide.
                    </p>

                    <p>
                        <span class="glyphicon glyphicon-earphone"></span> &nbsp; +88-09638-800-600
                    </p>
                    <p>
                        <span class="glyphicon glyphicon-envelope"></span> &nbsp; info@nobordersbd.com
                    </p>

                    <p><b>QUICK LINKS</b></p>

                    <a href=@Url.Action("Index", "Home")>FLIGHT</a> <br />
                    <a href=@Url.Action("About", "Home")>PACKAGE</a> <br />
                    <a href=@Url.Action("Contact", "Home")>VISA</a> <br />

                </div>

                <div class="col-md-4" style="min-height: 70px; border-left: 1px solid black ">
                    <p>
                        Find us on Facebook
                    </p>
                    <p>
                        <b><i>ABOUT US</i></b>
                    </p>

                    <a href="#">WHO ARE WE?</a> <br />
                    <a href="#">WHY US?</a> <br />
                    <a href="#">SERVICES</a> <br />
                    <a href="#">TERMS & CONDITIONS</a> <br /> <br/>

                    <p>
                        <b><i>LEGAL</i></b>
                    </p>

                    <a href="#">Transaction Confirmation</a> <br />
                    <a href="#">Amendment & Cancellation Policy</a> <br />
                    <a href="#">Privacy Policy </a> <br />
                </div>

            </div>


            <div class="row text-center">
                <div class="col-md-4">
                    <p> Developed By <a href="https://www.linkedin.com/in/samiul-siam-aa413a185/">SAS</a> & <a href="https://www.linkedin.com/in/ali-ahmed-akib-63bb91134/">AAA</a></p>
                </div>

                <div class="col-md-4">
                    <p>&copy; @DateTime.Now.Year - <a href="https://www.nobordersbd.com">NO BORDERS BD</a> All rights reserved.</p>
                </div>
                <div class="col-md-4">
                    Operational Address: Ka-4/1 (2<sup>nd</sup> Floor), Bashundhara Road, Dhaka-1229, Bangladesh.
                </div>
            </div>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>