FLYNOBORDERS.SelfB2B.Web/Controllers/AgentInfoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Windows.Forms;
using FLYNOBORDERS.SelfB2B.Entities;
using FLYNOBORDERS.SelfB2B.Framework.Constant;
using FLYNOBORDERS.SelfB2B.Web.Framework.Attributes;
using FLYNOBORDERS.SelfB2B.Web.Framework.Bases;
using FLYNOBORDERS.SelfB2B.Web.Framework.Utils;

namespace FLYNOBORDERS.SelfB2B.Web.Controllers
{
    [SELFB2BAuthorize(EnumCollection.UserTypeEnum.Admin)]
    public class AgentInfoController : BaseController
    {
        // GET: Admin
        public ActionResult List(string key = "")
        {
            /*if (MessageBox.Show("Are You Sure ?", "Confirmation", MessageBoxButtons.YesNo) == DialogResult.No)
                return RedirectToAction("Index", "Admin");*/
            var result = UserInfoRepo.PendingAgent(key);
            return View(result);
        }

        public ActionResult PendingDeposite(string key = "")
        {
            /*if (MessageBox.Show("Are You Sure ?", "Confirmation", MessageBoxButtons.YesNo) == DialogResult.No)
                return RedirectToAction("Index", "Admin");*/
            var result = DepositeRepo.GetAllPendingDeposite(key);
            return View(result);
        }

        public ActionResult AcceptPendingAgentDeposite(int pendingAgentId)
        {
            if (MessageBox.Show("Are You Sure ?", "Confirmation", MessageBoxButtons.YesNo) == DialogResult.No)
                return RedirectToAction("PendingDeposite");

            var result = DepositeRepo.AcceptByAdmin(pendingAgentId);

            if (result.HasError)
            {
                ViewBag.Error = result.Message;
                return RedirectToAction("PendingDeposite");
            }
            return RedirectToAction("PendingDeposite");
        }

    }
}

FLYNOBORDERS.SelfB2B.Web/Controllers/HotelController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Windows.Forms;
using FLYNOBORDERS.SelfB2B.Entities;
using FLYNOBORDERS.SelfB2B.Framework.Constant;
using FLYNOBORDERS.SelfB2B.Web.Framework.Attributes;
using FLYNOBORDERS.SelfB2B.Web.Framework.Bases;

namespace FLYNOBORDERS.SelfB2B.Web.Controllers
{
    [SELFB2BAuthorize(EnumCollection.UserTypeEnum.Admin)]
    public class HotelController : BaseController
    {
        // GET: Package

        public ActionResult Index()
        {
            return View(Context.HotelPictures.ToList());
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(HttpPostedFileBase file, HotelPicture emp)
        {
            
            string fileName = Path.GetFileName(file.FileName);
            string _filename = DateTime.Now.ToString("yymmssff") + fileName;

            string extension = Path.GetExtension(file.FileName);

            string path = Path.Combine(Server.MapPath("~/images/"), _filename);

            emp.Image = "~/images/" + _filename;


            /*if (extension.ToLower() == ".jpg" || extension.ToLower() == ".jpeg" || extension.ToLower() == ".png")
            {
                
            }
            else
            {
                ViewBag.msg = "Invalid Type";
            }  */

            /*if (file.ContentLength <= 100000)
            {
                
            }
            else
            {
                ViewBag.msg = "Image file should be equal or less than 1mb";
            }*/

            Context.HotelPictures.Add(emp);
            if (Context.SaveChanges() > 0)
            {
                file.SaveAs(path);
                ViewBag.msg = "Congratulations! HOTEL Added Successfully";
                ModelState.Clear();
            }
            return View();
        }


        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var p = Context.HotelPictures.Find(id);

            if (p == null)
            {
                return HttpNotFound();
            }
            Session["imgPath"] = p.Image;

            return View(p);
        }

        [HttpPost]
        public ActionResult Edit(HttpPostedFileBase file, HotelPicture emp)
        {
            //if (ModelState.IsValid)
            //{
            if (file != null)
            {
                string fileName = Path.GetFileName(file.FileName);
                string _filename = DateTime.Now.ToString("yymmssff") + fileName;

                string extension = Path.GetExtension(file.FileName);

                string path = Path.Combine(Server.MapPath("~/images/"), _filename);

                emp.Image = "~/images/" + _filename;


                /*if (extension.ToLower() == ".jpg" || extension.ToLower() == ".jpeg" || extension.ToLower() == ".png")
                {
                
                }
                else
                {
                    ViewBag.msg = "Invalid Type";
                }  */

                /*if (file.ContentLength <= 100000)
                {
                
                }
                else
                {
                    ViewBag.msg = "Image file should be equal or less than 1mb";
                } */

                Context.Entry(emp).State = EntityState.Modified;

                string oldImagePath = Request.MapPath(Session["imgPath"].ToString());

                if (Context.SaveChanges() > 0)
                {
                    file.SaveAs(path);

                    if (System.IO.File.Exists(oldImagePath))
                    {
                        System.IO.File.Delete(oldImagePath);
                    }
                    ViewBag.msg = "Hotel Updated Successfully";
                    return RedirectToAction("Index");
                }
            }
            else
            {
                emp.Image = Session["imgPath"].ToString();
                Context.Entry(emp).State = EntityState.Modified;

                if (Context.SaveChanges() > 0)
                {
                    TempData["msg"] = "Data Updated";
                    return RedirectToAction("Index");
                }
            }
            // }

            return View();
        }

        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var p = Context.HotelPictures.Find(id);

            if (p == null)
            {
                return HttpNotFound();
            }

            if (MessageBox.Show("Are You Sure ?", "Confirmation", MessageBoxButtons.YesNo) == DialogResult.No)
                return RedirectToAction("Index");

            string currentImage = Request.MapPath(p.Image);
            Context.Entry(p).State = EntityState.Deleted;

            if (Context.SaveChanges() > 0)
            {
                if (System.IO.File.Exists(currentImage))
                {
                    System.IO.File.Delete(currentImage);
                }
                ViewBag.msg = "Hotel Successfully Deleted";
                return RedirectToAction("Index");
            }
            return View(p);
        }
    }
}

FLYNOBORDERS.SelfB2B.Web/Controllers/PackageController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Windows.Forms;
using FLYNOBORDERS.SelfB2B.Entities;
using FLYNOBORDERS.SelfB2B.Framework.Constant;
using FLYNOBORDERS.SelfB2B.Web.Framework.Attributes;
using FLYNOBORDERS.SelfB2B.Web.Framework.Bases;

namespace FLYNOBORDERS.SelfB2B.Web.Controllers
{
    [SELFB2BAuthorize(EnumCollection.UserTypeEnum.Admin)]
    public class PackageController : BaseController
    {
        // GET: Package

        public ActionResult Index()
        {
            return View(Context.PackagePictures.ToList());
        }
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(HttpPostedFileBase file, PackagePicture emp)
        {
            
            string fileName = Path.GetFileName(file.FileName);
            string _filename = DateTime.Now.ToString("yymmssff") + fileName;

            string extension = Path.GetExtension(file.FileName);

            string path = Path.Combine(Server.MapPath("~/images/"), _filename);

            emp.Image = "~/images/" + _filename;


            /*if (extension.ToLower() == ".jpg" || extension.ToLower() == ".jpeg" || extension.ToLower() == ".png")
            {
                
            }
            else
            {
                ViewBag.msg = "Invalid Type";
            }  */

            /*if (file.ContentLength <= 100000)
            {
                
            }
            else
            {
                ViewBag.msg = "Image file should be equal or less than 1mb";
            }*/

            Context.PackagePictures.Add(emp);
            if (Context.SaveChanges() > 0)
            {
                file.SaveAs(path);
                ViewBag.msg = "Congratulations! Package Added Successfully";
                ModelState.Clear();
            }
            return View();
        }


        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var p = Context.PackagePictures.Find(id);

            if (p == null)
            {
                return HttpNotFound();
            }
            Session["imgPath"] = p.Image;

            return View(p);
        }

        [HttpPost]
        public ActionResult Edit(HttpPostedFileBase file, PackagePicture emp)
        {
            //if (ModelState.IsValid)
            //{
            if (file != null)
            {
                string fileName = Path.GetFileName(file.FileName);
                string _filename = DateTime.Now.ToString("yymmssff") + fileName;

                string extension = Path.GetExtension(file.FileName);

                string path = Path.Combine(Server.MapPath("~/images/"), _filename);

                emp.Image = "~/images/" + _filename;


                /*if (extension.ToLower() == ".jpg" || extension.ToLower() == ".jpeg" || extension.ToLower() == ".png")
                {
                
                }
                else
                {
                    ViewBag.msg = "Invalid Type";
                }  */

                /*if (file.ContentLength <= 100000)
                {
                
                }
                else
                {
                    ViewBag.msg = "Image file should be equal or less than 1mb";
                } */

                Context.Entry(emp).State = EntityState.Modified;

                string oldImagePath = Request.MapPath(Session["imgPath"].ToString());

                if (Context.SaveChanges() > 0)
                {
                    file.SaveAs(path);

                    if (System.IO.File.Exists(oldImagePath))
                    {
                        System.IO.File.Delete(oldImagePath);
                    }
                    ViewBag.msg = "Package Updated Successfully";
                    return RedirectToAction("Index");
                }
            }
            else
            {
                emp.Image = Session["imgPath"].ToString();
                Context.Entry(emp).State = EntityState.Modified;

                if (Context.SaveChanges() > 0)
                {
                    TempData["msg"] = "Data Updated";
                    return RedirectToAction("Index");
                }
            }
            // }

            return View();
        }

        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var p = Context.PackagePictures.Find(id);

            if (p == null)
            {
                return HttpNotFound();
            }

            if (MessageBox.Show("Are You Sure ?", "Confirmation", MessageBoxButtons.YesNo) == DialogResult.No)
                return RedirectToAction("Index");

            string currentImage = Request.MapPath(p.Image);
            Context.Entry(p).State = EntityState.Deleted;

            if (Context.SaveChanges() > 0)
            {
                if (System.IO.File.Exists(currentImage))
                {
                    System.IO.File.Delete(currentImage);
                }
                ViewBag.msg = "Package Successfully Deleted";
                return RedirectToAction("Index");
            }
            return View(p);
        }
    }
}

FLYNOBORDERS.SelfB2B.Web/Views/Admin/Index.cshtml
@using FLYNOBORDERS.SelfB2B.Framework.Helper

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>Index</h2>

<div class="row">
    
    @if (ValidationHelper2.IsValidString(ViewBag.Error))
    {
        <div class="alert alert-danger">
            @ViewBag.Error
        </div>
    }
    <div class="col-md-3">
        
        <div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">

            <div class="panel panel-primary">
                <div class="panel-heading" role="tab" id="headingOne">
                    <h4 class="panel-title">
                        <a style="text-decoration: none; display: block" role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
                            COMMON
                        </a>
                    </h4>
                </div>
                <div id="collapseOne" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingOne">
                    <div class="panel-body">
                        <a class="list-group-item" href="#navbar">
                            <span class="glyphicon glyphicon-th"></span> &nbsp; DASHBOARD
                        </a>
                        <a class="list-group-item" href="#navbar">
                            <span class="glyphicon glyphicon-eye-open"></span> &nbsp; DEPARTMENT
                        </a>
                        <a class="list-group-item" href="#navbar">
                            <span class="glyphicon glyphicon-book"></span> &nbsp; NEWS
                        </a>
                    </div>
                </div>
            </div>

            <div class="panel panel-primary">
                <div class="panel-heading" role="tab" id="headingTwo">
                    <h4 class="panel-title">
                        <a style="text-decoration: none; display: block" class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
                            FLY NOBORDERS
                        </a>
                    </h4>
                </div>
                <div id="collapseTwo" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingTwo">
                    <div class="panel-body">
                        <a class="list-group-item" href="#navbar" onclick="AddTab('PACKAGES', '@Url.Action("List", "AgentInfo")')">
                            <span class="glyphicon glyphicon-user"></span> &nbsp; AGENT INFO
                        </a>
                        <a class="list-group-item" href="#navbar" onclick="AddTab('PACKAGES', '@Url.Action("PendingDeposite", "AgentInfo")')">
                            <span class="glyphicon glyphicon-usd"></span> &nbsp; PENDING DEPOSITE
                        </a>
                        <a class="list-group-item" href="#navbar" onclick="AddTab('PACKAGES', '@Url.Action("Create", "Package")')">
                            <span class="glyphicon glyphicon-arrow-right"></span> &nbsp; LIST PACKAGES
                        </a>
                        <a class="list-group-item" href="#navbar" onclick="AddTab('HOTEL', '@Url.Action("Create", "Hotel")')">
                            <span class="glyphicon glyphicon-home"></span> &nbsp; LIST HOTEL
                        </a>
                        <a class="list-group-item" href="#navbar">
                            <span class="glyphicon glyphicon-earphone"></span> &nbsp; PHONE NUMBER
                        </a>
                    </div>
                </div>
            </div>

            <div class="panel panel-primary">
                <div class="panel-heading" role="tab" id="headingThree">
                    <h4 class="panel-title">
                        <a style="text-decoration: none; display: block" class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
                            USER MANAGER
                        </a>
                    </h4>
                </div>
                <div id="collapseThree" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingThree">
                    <div class="panel-body">
                        <a class="list-group-item" href="#navbar" onclick="AddTab('PendingUser', '@Url.Action("PendingUser", "Account")')">
                            <span class="glyphicon glyphicon-pencil"></span> &nbsp; PENDING USER
                        </a>
                        <a class="list-group-item" href="#navbar" onclick="AddTab('UserInfo', '@Url.Action("ListUserInfo", "Account")')">
                            <span class="glyphicon glyphicon-user"></span> &nbsp; USER INFO
                        </a>
                        <a class="list-group-item" href="#navbar" onclick="AddTab('UserBooking', '@Url.Action("List", "UserBooking")')">
                            <span class="glyphicon glyphicon-ok"></span> &nbsp; USER BOOKING
                        </a>
                    </div>
                </div>
            </div>

        </div>

    </div>

    <div class="col-md-9" style="min-height: 500px; border-left: 1px solid gray">
        
        <div>

            <!-- Nav tabs -->
            <ul id="sideMenu" class="nav nav-tabs" role="tablist">
                <li role="presentation" class="active" id="li1"><a href="#div1" aria-controls="home" role="tab" data-toggle="tab">Dashboard</a></li>
            </ul>

            <!-- Tab panes -->
            <div class="tab-content" id="mainTab">
                <div role="tabpanel" class="tab-pane active" id="div1">
                    Dashboard
                </div>
            </div>

        </div>

    </div>
</div>


@section scripts{
    <script>

        var i = 2;
        function AddTab(tabName, link) {
            var height = $(document).height - 80;
            $('#sideMenu').append('<li role="presentation" id="li' + i + '"><a href="#div' + i + '" aria-controls="home" role="tab" data-toggle="tab">' + tabName + ' &nbsp; &nbsp; <span style="cursor: pointer" class="glyphicon glyphicon-remove" onclick="RemoveTab('+i+')"></span></a></li>');
            $('#mainTab').append('<div role="tabpanel" class="tab-pane" id="div' + i + '"><iframe src="'+link+'" width="100%" height="500"></iframe></div>');
            $('#sideMenu a:last').tab('show') // Select last tab
            i++;
        }

        function RemoveTab(index) {

            if ($('#li' + index).hasClass('active')) {
                var prevLi = $('#li' + index).prev();
                var prevDiv = $('#div' + index).prev();

                prevLi.addClass('active');
                prevDiv.addClass('active');
            }


            $('#li' + index).remove();
            $('#div' + index).remove();
        }
    </script>
}

FLYNOBORDERS.SelfB2B.Web/Views/Admin/UserProfile.cshtml
@using FLYNOBORDERS.SelfB2B.Framework.Constant
@using FLYNOBORDERS.SelfB2B.Framework.Helper
@model FLYNOBORDERS.SelfB2B.Framework.Object.Result<FLYNOBORDERS.SelfB2B.Entities.UserInfo>
@{
    ViewBag.Title = "UserProfile";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2 align="center">MY PROFILE</h2>

@using (Html.BeginForm("UserProfile"))
{
    <div class="row">
        
        <div class="col-md-1"></div>

        <div class="col-md-9">
            
            @if (ValidationHelper2.IsValidString(ViewBag.Error))
            {
                <div class="alert alert-danger">
                    @ViewBag.Error
                </div>
            }
            
            <div class="panel box-shadow">
                <div class="panel-heading" style="width: 100%; border-bottom: 1px solid gray">
                    <span class="glyphicon glyphicon-user"></span> &nbsp; COMPANY INFORMATION
                </div>
                <div class="panel-body">
                    <div class="row">
                        <div class="col-md-3">
                            <div class="form-group" align="center">
                                @Html.LabelFor(e => e.Data.CompanyInfo.CName)
                                @Html.TextBoxFor(e => e.Data.CompanyInfo.CName, new { @class = "form-control" })
                                @Html.ValidationMessageFor(e => e.Data.CompanyInfo.CName)
                                @Html.HiddenFor(e => e.Data.CompanyInfo.TradeLicenseNo)
                            </div>
                        </div>

                        <div class="col-md-3">
                            <div class="form-group" align="center">
                                @Html.LabelFor(e => e.Data.CompanyInfo.CEmail)
                                @Html.TextBoxFor(e => e.Data.CompanyInfo.CEmail, new { @class = "form-control" })
                                @Html.ValidationMessageFor(e => e.Data.CompanyInfo.CEmail)
                            </div>
                        </div>

                        <div class="col-md-3">
                            <div class="form-group" align="center">
                                @Html.LabelFor(e => e.Data.CompanyInfo.Website)
                                @Html.TextBoxFor(e => e.Data.CompanyInfo.Website, new { @class = "form-control" })
                                @Html.ValidationMessageFor(e => e.Data.CompanyInfo.Website)
                            </div>
                        </div>

                        <div class="col-md-3">
                            <div class="form-group" align="center">
                                @Html.LabelFor(e => e.Data.CompanyInfo.PhnNumber)
                                @Html.TextBoxFor(e => e.Data.CompanyInfo.PhnNumber, new { @class = "form-control" })
                                @Html.ValidationMessageFor(e => e.Data.CompanyInfo.PhnNumber)
                                @Html.HiddenFor(e => e.Data.CompanyInfo.Address)
                                @Html.HiddenFor(e => e.Data.CompanyInfo.City)
                                @Html.HiddenFor(e => e.Data.CompanyInfo.Zip)
                                @Html.HiddenFor(e => e.Data.Balance)
                            </div>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-md-1">
                            <label style="text-align: center; font-size: 100%">Address:</label>
                        </div>
                        <div class="col-md-11">
                            <label class="form-control"> @Model.Data.CompanyInfo.Address, @Model.Data.CompanyInfo.City, @Model.Data.CompanyInfo.Zip</label>
                        </div>
                    </div>
                </div>

            </div>
            
            <div class="panel box-shadow">               
                <div class="panel-heading" style="width: 100%; border-bottom: 1px solid gray">
                    <span class="glyphicon glyphicon-user"></span> &nbsp; USER PROFILE
                </div>
                <div class="panel-body">
                    <div class="row">
                        <div class="col-md-3">
                            <div class="form-group" align="center">
                                @Html.LabelFor(e => e.Data.FirstName)
                                @Html.TextBoxFor(e => e.Data.FirstName, new { @class = "form-control" })
                                @Html.ValidationMessageFor(e => e.Data.FirstName)
                                @Html.HiddenFor(e=>e.Data.UID)
                                @Html.HiddenFor(e=>e.Data.CompanyInfo.CID)
                                @Html.HiddenFor(e=>e.Data.CompanyID)
                                @Html.HiddenFor(e=>e.Data.AdminVerifyID)
                                @Html.HiddenFor(e=>e.Data.UserTypeID)
                                @Html.HiddenFor(e=>e.Data.TimeZone)
                            </div>
                        </div>

                        <div class="col-md-3">
                            <div class="form-group" align="center">
                                @Html.LabelFor(e => e.Data.LastName)
                                @Html.TextBoxFor(e => e.Data.LastName, new { @class = "form-control" })
                                @Html.ValidationMessageFor(e => e.Data.LastName)
                            </div>
                        </div>

                        <div class="col-md-3">
                            <div class="form-group" align="center">
                                @Html.LabelFor(e => e.Data.UEmail)
                                @Html.TextBoxFor(e => e.Data.UEmail, new { @class = "form-control" })
                                @Html.ValidationMessageFor(e => e.Data.UEmail)
                            </div>
                        </div>

                        <div class="col-md-3">
                            <div class="form-group" align="center">
                                @Html.LabelFor(e => e.Data.PreferredRoe)
                                @Html.DropDownListFor(p => p.Data.PreferredRoe, new SelectList(EnumCollection.GetEnumList(typeof(EnumCollection.PreferredRoeEnum)), "ID", "Name"), "Please Select Preferred ROE", new { @class = "form-control" })
                                @*@Html.TextBoxFor(e => e.Data.PreferredRoe, new { @class = "form-control" })*@
                                @Html.ValidationMessageFor(e => e.Data.PreferredRoe)
                            </div>
                        </div>
                    </div>
                </div>

            </div>

            <div class="panel box-shadow">
                <div class="panel-heading" style="width: 100%; border-bottom: 1px solid gray">
                    <span class="glyphicon glyphicon-log-in"></span> &nbsp; CHANGE PASSWORD
                </div>
                <div class="panel-body">
                    <div class="row">
                        <div class="col-md-4">
                            <div class="form-group" align="center">
                                @Html.LabelFor(e => e.Data.UEmail)
                                @Html.TextBoxFor(e => e.Data.UEmail, new { @class = "form-control" })
                                @Html.ValidationMessageFor(e => e.Data.UEmail)
                            </div>
                        </div>

                        <div class="col-md-4">
                            <a href="" class="btn btn-info">CHANGE PASSWORD</a>
                            @*<div class="form-group" align="center">
                                @Html.LabelFor(e => e.Data.Pass)
                                <input type="password" value=@Model.Data.Pass name="Pass" class="form-control" />
                                @Html.ValidationMessageFor(e => e.Data.Pass)
                            </div>*@
                                        </div>

                                        @*<div class="col-md-4">
                            <div class="form-group" align="center">
                                @Html.LabelFor(e => e.Data.Pass)
                                <input type="password" value=@Model.Data.Pass name="CPass" class="form-control" />
                                @Html.ValidationMessageFor(e => e.Data.Pass)
                            </div>
                        </div>*@
                    </div>
                </div>

            </div>

            
        </div>

        <div class="col-md-2">
            <div class="box-shadow">
                <div align="center" style="width: 100%; border-bottom: 1px solid gray">
                    <label>@Model.Data.LastName, @Model.Data.FirstName</label>
                </div>

                <div class="row">
                    <div class="col-md-6">
                        <label style="font-size: 85%">ROLE: </label>
                    </div>

                    <div class="col-md-6">
                        @if (Model.Data.UserTypeID == (int)EnumCollection.UserTypeEnum.Admin)
                        {
                            <label style="font-size: 85%">ADMIN</label>
                        }

                        @if (Model.Data.UserTypeID == (int)EnumCollection.UserTypeEnum.Agent)
                        {
                            <label style="font-size: 85%">AGENT</label>
                        }

                    </div>
                </div>

                <div class="row">
                    <div class="col-md-6">
                        <label style="font-size: 85%">STATUS: </label>
                    </div>

                    <div class="col-md-6">
                        <label style="font-size: 85%">ACTIVE</label>
                    </div>
                </div>

                <div class="row">
                    <div class="col-md-12">
                        <button type="submit" class="btn btn-primary form-control">UPDATE</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
}